### ISSUE TITLE
Загрузка карты полностью завязана на yandex.st

### ISSUE THREAD

**Issue by d1g** [ErshKUS/OpenStreetMap.ru#255]
Два файла в </head> нужно отдавать со своего домена openstreetmap.ru

http://yandex.st/jquery/1.8.2/jquery.min.js
http://yandex.st/jquery-ui/1.9.0/jquery-ui.min.js

чтобы не было зависимости от yandex.st либо откладывать загрузку jquery ui: https://developers.google.com/speed/pagespeed/service/DeferJavaScript

Имеет смысл заодно выделить домен под "статику" либо вот это поставить: https://developers.google.com/speed/pagespeed/module/

**Comment by freeExec** [comment]
Да, наличие яндекса напрягает.
